from django import forms

from marketanalyzer.models import LPitems, regions

# Form used for uploading market dumps.
class UploadFileForm(forms.Form):
    file  = forms.FileField()

# Form to get list of item(s) for the LP calculator.
class LPCalcItem(forms.Form):
    # 'size' attr is height of widget (# of entries visible)
    item = forms.MultipleChoiceField(choices=LPitems,
                                     widget=forms.SelectMultiple(
                                        attrs={'size': 30}))
    spendable = forms.IntegerField() # the amt of LP available to spend

# Form to choose the region and price statistic for each item to use in
# calculations.
class LPCalcDetails(forms.Form):
    # Available price stat options. These are all generated by SQL aggregate
    # functions performed on a filtered query.
    __priceStats = (
        ('meanbp', 'Mean Buy Price'),
        #('medbp', 'Median Buy Price'),
        ('hbp', 'High Buy Price'),
        ('lbp', 'Low Buy Price'),
        ('meansp', 'Mean Sell Price'),
        #('medsp', 'Median Sell Price'),
        ('hsp', 'High Sell Price'),
        ('lsp', 'Low Sell Price')
    )
    region = forms.MultipleChoiceField(choices=regions)
    stat = forms.ChoiceField(choices=__priceStats)
    item_name = ''